export enum ConversionMode {
  SAME = 'SAME',
  TYPE_SAME_COIN_DIFFERENT = 'TYPE_SAME_COIN_DIFFERENT',
  CUSTOM_TO_DYNAMIC = 'CUSTOM_TO_DYNAMIC',
  DYNAMIC_TO_CUSTOM = 'DYNAMIC_TO_CUSTOM',
  DYNAMIC_TO_DYNAMIC = 'DYNAMIC_TO_DYNAMIC',
}
