import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import mongoose, { Model, Types } from 'mongoose';
import { Token } from '../token/schemas/token.schema';
import { Wallet } from '../wallet/schemas/wallet.schema';
import { WalletTransaction } from '../wallet/schemas/wallet.transaction.schema.';
import { WithdrawTransaction } from '../wallet/schemas/withdraw.transaction.schema';
import { TrxType } from '../global/enums/trx.type.enum';
import { TransactionFlow } from '../wallet/enums/transcation.flow.enum';
import { RequestStatus } from '../wallet/enums/request.status.enum';

async function bootstrap() {
  console.log('Starting transaction processing script...');
  const appContext = await NestFactory.createApplicationContext(AppModule);

  try {
    // Get model instances
    const WithdrawTransactionModel = appContext.get<Model<WithdrawTransaction>>(
      WithdrawTransaction.name + 'Model',
    );
    const walletTransactionModel = appContext.get<Model<WalletTransaction>>(
      WalletTransaction.name + 'Model',
    );

    console.log('Fetching withdraw transactions...');
    const findAllWithdrawTransactions = await WithdrawTransactionModel.find({
      metaAmount: { $exists: true },
      requestStatus: RequestStatus.REJECTED_AND_REIMBERSED,
      deletedAt: null,
    });

    console.log(
      `Found ${findAllWithdrawTransactions.length} transactions to process`,
    );

    if (findAllWithdrawTransactions.length > 0) {
      for (const element of findAllWithdrawTransactions) {
        console.log(`Processing transaction ID: ${element._id}`);

        // Find matching reimbursement transactions
        const reimburseTransactions = await walletTransactionModel.findOne({
          user: element.user,
          wallet: element.fromWallet,
          amount: element.metaAmount,
          trxType: TrxType.REIMBERS,
          transactionFlow: TransactionFlow.IN,
          deletedAt: null,
        });

        if (reimburseTransactions) {
          console.log(
            `Updating reimbursement amount for transaction ${element._id} from ${element.metaAmount} to ${element.amount}`,
          );

          try {
            await reimburseTransactions.updateOne({
              $set: {
                amount: element.amount,
                meta: {
                  oldAmount: reimburseTransactions.amount,
                  newAmount: element.amount,
                  fee: element?.fee || 0,
                  commission: element?.commission || 0,
                  withdrawType: element.withdrawType,
                },
                note: `reimburse fixes from ${reimburseTransactions.amount} to ${element.amount} Auto generated by Script when amount and total is reversed`,
              },
            });
            console.log('Successfully updated reimbursement amount');
          } catch (updateError) {
            console.error('Error updating reimbursement:', updateError);
          }
        } else {
          console.log(
            `No matching reimbursement found for transaction ${element._id}`,
          );
        }
      }
    }

    console.log('Transaction processing completed successfully');
  } catch (error) {
    console.error('An error occurred during transaction analysis:', error);
    throw error; // Re-throw to be caught by the bootstrap catch block
  } finally {
    console.log('Closing application context...');
    await appContext.close();
    process.exit(0);
  }
}

bootstrap()
  .then(() => {
    console.log('Script execution completed successfully');
    process.exit(0);
  })
  .catch((err) => {
    console.error('Unhandled error during script execution:', err);
    process.exit(1);
  });
