export enum NotificationTypeEnum {
  COMING_SOON = 'coming-soon',
  TRANSACTION = 'transaction',
  OTHERS = 'others',
  WITHDRAWAL = 'withdrawal',
  DEPOSIT = 'deposit',
  TRANSFER = 'transfer',
  SWAP = 'swap',
  SPECIAL_SWAP = 'special-swap',
  STAKE = 'stake',
  CLAIMED_REWARD = 'claimed-reward',
  REWARD = 'reward',
  DEVICE_LOGGED_IN = 'device-logged-in',
  REGISTRATION = 'registration',
  PROFILE_UPDATE = 'profile-update',
  CHANGE_EMAIL = 'change-email',
  CHANGE_PASSWORD = 'change-password',
  PROFILE_IMAGE_UPLOAD = 'profile-image-upload',
  KYC_APPROVED = 'kyc-approved',
  KYC_REJECTED = 'kyc-rejected',
  DEPOSIT_AND_STAKE = 'deposit-and-stake',
}
